### ISSUE TITLE
MoP and KoP cannot be used together

### ISSUE THREAD

**Issue by fanyouyong0526** [streamnative/mop#132]
Add
 **brokerentrymetadatainterceptors = org. Apache. Pulsar. Common. Intercept. Appendindexmetadatainterceptor** 
to the configuration file
Cannot subscribe to published messages through MQTT

**Comment by Technoboy-** [comment]
Hi, Could you give more description about your issue?
I have tried to set the above interceptor, it's working in my local.

**Comment by fanyouyong0526** [comment]
KoP needs to be added after version 2.80

**brokerentrymetadatainterceptors = org. Apache. Pulsar. Common. Intercept. Appendindexmetadatainterceptor**

KoP works normally, but when I add MoP, the mqtt client can publish messages normally, but cannot subscribe to messages
ERROR：
_**java.lang.IllegalArgumentException: Invalid unknonwn tag type: 6
        at org.apache.pulsar.common.api.proto.LightProtoCodec.skipUnknownField(LightProtoCodec.java:270) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.common.api.proto.MessageMetadata.parseFrom(MessageMetadata.java:1370) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:426) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:416) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
        at io.streamnative.pulsar.handlers.mqtt.utils.PulsarMessageConverter.toMqttMessages(PulsarMessageConverter.java:71) ~[?:?]
        at io.streamnative.pulsar.handlers.mqtt.support.MQTTConsumer.sendMessages(MQTTConsumer.java:85) ~[?:?]
        at io.streamnative.pulsar.handlers.mqtt.support.MQTTConsumer.sendMessages(MQTTConsumer.java:41) ~[?:?]
        at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:538) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:469) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.mledger.impl.OpReadEntry.lambda$checkReadCompletion$2(OpReadEntry.java:156) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]**_

**Comment by liangyuanpeng** [comment]
I think you can provide more info for this, some like your topic, qos, etc.. 

And you use mqtt consumer and mqtt producer, right?  

mqtt producer --> mqtt connsumer

**Comment by fanyouyong0526** [comment]
![image](https://user-images.githubusercontent.com/57142554/132472259-40a6bdca-777a-443d-b690-e053a9c7daa1.png)
When I use the above configuration, remove it

**brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor**

MQTT clients can publish and subscribe to messages
![image](https://user-images.githubusercontent.com/57142554/132473544-0d3da866-c6e6-4a79-856d-0cd3fe6104f8.png)
![image](https://user-images.githubusercontent.com/57142554/132473639-4d94abdb-c260-417a-9623-97effcef45ed.png)
but, Kafka cannot publish and subscribe messages .
![image](https://user-images.githubusercontent.com/57142554/132474510-cc01ed24-4d7c-49da-bd77-1f9438277696.png)
If I modify the configuration as above add it
**brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor**
Kafka client can publish and subscribe messages.
but the mqtt client can publish messages normally, cannot subscribe to messages
![image](https://user-images.githubusercontent.com/57142554/132475380-9eb1a295-ef2c-4689-8fa9-0dc9d4d02d3a.png)
![image](https://user-images.githubusercontent.com/57142554/132475465-4aa20c80-1fea-4919-84cc-1b939f9c1fba.png)
View the broker log with the following error message:

**_java.lang.IllegalArgumentException: Invalid unknonwn tag type: 6
at org.apache.pulsar.common.api.proto.LightProtoCodec.skipUnknownField(LightProtoCodec.java:270) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
at org.apache.pulsar.common.api.proto.MessageMetadata.parseFrom(MessageMetadata.java:1370) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:426) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:416) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
at io.streamnative.pulsar.handlers.mqtt.utils.PulsarMessageConverter.toMqttMessages(PulsarMessageConverter.java:71) ~[?:?]
at io.streamnative.pulsar.handlers.mqtt.support.MQTTConsumer.sendMessages(MQTTConsumer.java:85) ~[?:?]
at io.streamnative.pulsar.handlers.mqtt.support.MQTTConsumer.sendMessages(MQTTConsumer.java:41) ~[?:?]
at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:538) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:469) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
at org.apache.bookkeeper.mledger.impl.OpReadEntry.lambda$checkReadCompletion$2(OpReadEntry.java:156) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]_**

**Comment by fanyouyong0526** [comment]
The above is the detailed configuration and information.
I'm using a local build nar.
commit id is  **f6602d8a5ff567e880f0057aea3176a9a68500d2**
@Technoboy-

**Comment by fanyouyong0526** [comment]
I  tried to update the latest version of the mop code and found that the MQTT client could not subscribe to the messages with or without the addition of **brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor**
 to the configuration file

**Comment by codelipenghui** [comment]
@fanyouyong0526 Which Pulsar version are you using, please make sure the Pulsar version is the same as the mop plugin version.

**Comment by codelipenghui** [comment]
@Technoboy- Looks we need to add an integration test in the streamnative-tests to make sure MoP can work with KoP together.

**Comment by fanyouyong0526** [comment]
pulsar version：2.8.0
mop：A locally built version，commitid is f6602d8a5ff567e880f0057aea3176a9a68500d2

**Comment by BewareMyPower** [comment]
Could you try 2.8.1? It's because `Commands#parseMessageMetadata` didn't skip the BrokerEntryMetadata in 2.8.0, but https://github.com/apache/pulsar/pull/10968 add the `skipBrokerEntryMetadataIfExist` call in `parseMessageMetadata`. After that, `parseMessageMetadata` should work.

**Comment by Technoboy-** [comment]
Please upgrade pulsar to 2.8.1.
