### ISSUE TITLE
Metrics url 404

### ISSUE THREAD

**Issue by liweiv** [streamnative/mop#347]
**Describe the bug**
Pulsar 2.8.1 
mop 2.8.1.30
curl webservice url and  port (default 8080)     IP:8080/mop-stats return 404

**Comment by liweiv** [comment]
curl IP:8080/mop-stats/  also  return 404,
But curl IP:8080/metrics for prometheus  is ok.

**Comment by mattisonchao** [comment]
@liweiv 

I will try to reproduce it first.

**Comment by mattisonchao** [comment]
@liweiv  

Maybe you need to add the following configuration to broker.conf or standalone.conf:

```
additionalServlets=mqtt-servlet
additionalServletDirectory=[protocolHandlerDir]
```

**Comment by mattisonchao** [comment]
But I got some error when i use this configuration. 

I need to fix it.

**Comment by Technoboy-** [comment]
> @liweiv
> 
> Maybe you need to add the following configuration to broker.conf or standalone.conf:
> 
> ```
> additionalServlets=mqtt-servlet
> additionalServletDirectory=[protocolHandlerDir]
> ```

Yes, right.

**Comment by Technoboy-** [comment]
> But I got some error when i use this configuration.
> 
> I need to fix it.
> 
> > @liweiv
> > Maybe you need to add the following configuration to broker.conf or standalone.conf:
> > ```
> > additionalServlets=mqtt-servlet
> > additionalServletDirectory=[protocolHandlerDir]
> > ```

Any other issue, you can open a new issue.

**Comment by liweiv** [comment]
@mattisonchao 
A class cast error occured after adding the configuration.
```
additionalServlets=mqtt-servlet
additionalServletDirectory=./protocls
```
Error info:
```
Caused by:
java.lang.ClassCastException: class io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler cannot be cast to class io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler (io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @2e674698; io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @5f59b6c5)
	at io.streamnative.pulsar.handlers.mqtt.MQTTServiceServlet.getMetricsCollector(MQTTServiceServlet.java:47)
	at io.streamnative.pulsar.handlers.mqtt.MQTTServiceServlet.doGet(MQTTServiceServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:67)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
```
