### ISSUE TITLE
NPE when unsubscribe in proxy mode.

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#384]
## Stack trace
```
21:42:48.204 [pulsar-io-76-2:org.apache.pulsar.broker.service.nonpersistent.NonPersistentSubscription@391] ERROR org.apache.pulsar.broker.service.nonpersistent.NonPersistentSubscription - [non-persistent://public/default/a%2Fb][7f000001d49c61d44ed8] Error deleting subscription
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_291]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_291]
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1643) [?:1.8.0_291]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) [?:1.8.0_291]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) [netty-common-4.1.67.Final.jar:4.1.67.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.67.Final.jar:4.1.67.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.67.Final.jar:4.1.67.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.67.Final.jar:4.1.67.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.67.Final.jar:4.1.67.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.67.Final.jar:4.1.67.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
	at org.apache.pulsar.broker.service.nonpersistent.NonPersistentTopic.lambda$unsubscribe$48(NonPersistentTopic.java:1006) ~[pulsar-broker-2.9.0-rc-202110221101.jar:2.9.0-rc-202110221101]
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1640) ~[?:1.8.0_291]
	... 9 more
```

**Comment by mattisonchao** [comment]
@Technoboy- 

I think we forgot to update the netty attribute ``topicSubscriptions``, and an exception occurred calling ``processConnectionLost`` to invoke ``unsubscribe`` twice.

```java
// Connection
    private void doRemoveSubscriptions() {
        Map<Topic, Pair<Subscription, Consumer>> topicSubscriptions = NettyUtils
                .getTopicSubscriptions(channel);
        // For producer doesn't bind subscriptions
        if (topicSubscriptions != null) {
            topicSubscriptions.forEach((k, v) -> {
                k.unsubscribe(this.clientId);
                v.getLeft().delete();
            });
        }
    }
```


```java
// DefaultProtocolMethodProcessorImpl
    @Override
    public void processConnectionLost() {
        if (connection == null) {
            channel.close();
            return;
        }
        String clientId = connection.getClientId();
        if (log.isDebugEnabled()) {
            log.debug("[Connection Lost] [{}] ", clientId);
        }
        metricsCollector.removeClient(NettyUtils.getAddress(channel));
        connectionManager.removeConnection(connection);
        connection.removeSubscriptions();
        subscriptionManager.removeSubscription(clientId);
        WillMessage willMessage = connection.getWillMessage();
        if (willMessage != null) {
            fireWillMessage(willMessage);
        }
    }
```

**Comment by mattisonchao** [comment]
@Technoboy- 

i can fix it later, if nobody fix it.

**Comment by Technoboy-** [comment]
> @Technoboy-
> 
> I think we forgot to update the netty attribute `topicSubscriptions`, and an exception occurred calling `processConnectionLost` to invoke `unsubscribe` twice.
> 
> ```java
> // Connection
>     private void doRemoveSubscriptions() {
>         Map<Topic, Pair<Subscription, Consumer>> topicSubscriptions = NettyUtils
>                 .getTopicSubscriptions(channel);
>         // For producer doesn't bind subscriptions
>         if (topicSubscriptions != null) {
>             topicSubscriptions.forEach((k, v) -> {
>                 k.unsubscribe(this.clientId);
>                 v.getLeft().delete();
>             });
>         }
>     }
> ```
> 
> ```java
> // DefaultProtocolMethodProcessorImpl
>     @Override
>     public void processConnectionLost() {
>         if (connection == null) {
>             channel.close();
>             return;
>         }
>         String clientId = connection.getClientId();
>         if (log.isDebugEnabled()) {
>             log.debug("[Connection Lost] [{}] ", clientId);
>         }
>         metricsCollector.removeClient(NettyUtils.getAddress(channel));
>         connectionManager.removeConnection(connection);
>         connection.removeSubscriptions();
>         subscriptionManager.removeSubscription(clientId);
>         WillMessage willMessage = connection.getWillMessage();
>         if (willMessage != null) {
>             fireWillMessage(willMessage);
>         }
>     }
> ```

SimpleIntegrationTest#testSimpleMqttPubAndSubQos0 can reproduce. It's related to non-persistent topic.

**Comment by Technoboy-** [comment]
> @Technoboy-
> 
> I think we forgot to update the netty attribute `topicSubscriptions`, and an exception occurred calling `processConnectionLost` to invoke `unsubscribe` twice.
> 
> ```java
> // Connection
>     private void doRemoveSubscriptions() {
>         Map<Topic, Pair<Subscription, Consumer>> topicSubscriptions = NettyUtils
>                 .getTopicSubscriptions(channel);
>         // For producer doesn't bind subscriptions
>         if (topicSubscriptions != null) {
>             topicSubscriptions.forEach((k, v) -> {
>                 k.unsubscribe(this.clientId);
>                 v.getLeft().delete();
>             });
>         }
>     }
> ```
> 
> ```java
> // DefaultProtocolMethodProcessorImpl
>     @Override
>     public void processConnectionLost() {
>         if (connection == null) {
>             channel.close();
>             return;
>         }
>         String clientId = connection.getClientId();
>         if (log.isDebugEnabled()) {
>             log.debug("[Connection Lost] [{}] ", clientId);
>         }
>         metricsCollector.removeClient(NettyUtils.getAddress(channel));
>         connectionManager.removeConnection(connection);
>         connection.removeSubscriptions();
>         subscriptionManager.removeSubscription(clientId);
>         WillMessage willMessage = connection.getWillMessage();
>         if (willMessage != null) {
>             fireWillMessage(willMessage);
>         }
>     }
> ```

It may be called twice.
