### ISSUE TITLE
[Proxy] Publish message fail when proxy disconnect from the broker.

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/mop#498]
**Describe the bug**
When broker topics unload or some other behaviour, it will close proxy connection. but proxy doesn't do any action like reconnect/disconnect to the client. 
So, in this time. producer publish message will fail and see the error here.

```java
2022-03-03T23:43:50,207+0000 [pulsar-client-io-68-1] ERROR io.streamnative.pulsar.handlers.mqtt.proxy.MQTTProxyProtocolMethodProcessor - [Proxy Publish] Failed to publish for topic : bench/6481, CId : ip-10-0-0-64_bench_pub_6481_1675243598
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: Lookup request timeout {'durationMs': '30000', 'reqId':'3112562561116842152', 'remote':'ip-10-0-0-232.cn-north-1.compute.internal/10.0.0.232:6650', 'local':'/10.0.0.232:54366'}
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1204) ~[org.apache.pulsar-pulsar-client-original-2.9.1.jar:2.9.1]
	at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:53) [org.apache.pulsar-pulsar-common-2.9.1.jar:2.9.1]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by mattisonchao** [comment]
@Technoboy-  
This issue looks related to #497.

But we may have another problem:

when the broker closes the connection to the proxy exchanger, we do not remove or reconnect this exchange.

**Comment by Technoboy-** [comment]
> @Technoboy- This issue looks related to #497.

Yes, right. Closed.
