### ISSUE TITLE
Non-persistent topic disconnect will trigger NPE

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#558]
### Reproduce Test

Put below test method to `SimpleIntegrationTest`.
```
@Test
public void testNonPersistentTopic() throws Exception {
    String topicName = "non-persistent://public/default/a/b";
    MQTT mqtt = createMQTTClient();
    BlockingConnection connection = mqtt.blockingConnection();
    connection.connect();
    Topic[] topics = { new Topic(topicName, QoS.AT_LEAST_ONCE) };
    connection.subscribe(topics);
    String message = "Hello MQTT";
    connection.publish(topicName, message.getBytes(), QoS.AT_LEAST_ONCE, false);
    Message received = connection.receive();
    Assert.assertEquals(received.getTopic(), topicName);
    Assert.assertEquals(new String(received.getPayload()), message);
    received.ack();
    connection.disconnect();
}
```

### Stack Trace
```
09:58:23.057 [pulsar-load-manager-3-1:org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl@461] INFO  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Writing local data to metadata store because maximum change 100.0% exceeded threshold 10%; time since last report written is 41.002 seconds
09:58:23.048 [pulsar-io-6-8:org.apache.pulsar.broker.service.nonpersistent.NonPersistentSubscription@390] ERROR org.apache.pulsar.broker.service.nonpersistent.NonPersistentSubscription - [non-persistent://public/default/a%2Fb][7f000001dc71623a7e39] Error deleting subscription
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1739) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) [?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at org.apache.pulsar.broker.service.nonpersistent.NonPersistentTopic.lambda$unsubscribe$54(NonPersistentTopic.java:1065) ~[pulsar-broker-2.10.0.0-rc4.jar:2.10.0.0-rc4]
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736) ~[?:?]
	... 9 more
```

**Comment by mattisonchao** [comment]
@Technoboy-  
I will try to fix it.

**Comment by JoeCqupt** [comment]
#561 
PTAL @Technoboy-

**Comment by Technoboy-** [comment]
Hi @JoeCqupt ：
Thanks for your contribution. After diving into the codes, I find that it's non-persistent topic issue in Pulsar. not MoP.
When disconnect, MoP will first unsubscribe then delete (if cleanSession).  If the current topic is non-persistent, there is a race condition in Pulsar :
```
@Override
    public CompletableFuture<Void> unsubscribe(String subscriptionName) {
        // checkInactiveSubscriptions iterates over subscriptions map and removing from the map with the same thread.
        // That creates deadlock. so, execute remove it in different thread.
        return CompletableFuture.runAsync(() -> {
            NonPersistentSubscription sub = subscriptions.remove(subscriptionName);
            // preserve accumulative stats form removed subscription
            SubscriptionStatsImpl stats = sub.getStats();
            bytesOutFromRemovedSubscriptions.add(stats.bytesOutCounter);
            msgOutFromRemovedSubscriptions.add(stats.msgOutCounter);
        }, brokerService.executor());
    }
```
`subscriptions` will remove twice for `unsubscribe` and `delete`.
