### ISSUE TITLE
Flaky-test: [ProxyTest].[testProxyProcessPingReq]

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/mop#578]
[ProxyTest] is flaky. The [testProxyProcessPingReq] test method fails sporadically.

[example failure](https://github.com/streamnative/mop/runs/5869665764?check_suite_focus=true)

```java
Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 143.938 s <<< FAILURE! - in io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.proxy.ProxyTest
Error:  testProxyProcessPingReq(io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.proxy.ProxyTest)  Time elapsed: 4.221 s  <<< FAILURE!
java.lang.AssertionError: expected [1.0] but found [2.0]
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 143.938 s <<< FAILURE! - in io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.proxy.ProxyTest
Error:  testProxyProcessPingReq(io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.proxy.ProxyTest)  Time elapsed: 4.221 s  <<< FAILURE!
java.lang.AssertionError: expected [1.0] but found [2.0]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:442)
	at io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.proxy.ProxyTest.testProxyProcessPingReq(ProxyTest.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:[415](https://github.com/streamnative/mop/runs/5869665764?check_suite_focus=true#step:6:415))
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:[418](https://github.com/streamnative/mop/runs/5869665764?check_suite_focus=true#step:6:418))
</pre></code>
</details>

**Comment by Technoboy-** [comment]
Fixed in #588
