### ISSUE TITLE
ClassNotFound from locally built Pulsar standalone

### ISSUE THREAD

**Issue by andrekramer1** [streamnative/mop#61]
Hi, I've added the .nar file to ./protocol in a local build of Pulsar and am getting a class not found exception when running ./bin/pulsar standalone. Your help is greatly appreciated!

13:01:55.325 [pulsar-io-29-1] INFO  io.streamnative.pulsar.handlers.mqtt.support.ProtocolMethodProcessorImpl - [Subscribe] [[id: 0xe2f7eae5, L:/127.0.0.1:1883 - R:/127.0.0.1:58408]] msg: MqttSubscribeMessage[fixedHeader=MqttFixedHeader[messageType=SUBSCRIBE, isDup=false, qosLevel=AT_LEAST_ONCE, isRetain=false, remainingLength=41], variableHeader=MqttMessageIdVariableHeader[messageId=1], payload=MqttSubscribePayload[MqttTopicSubscription[topicFilter=persistent://public/default/my-topic, qualityOfService=AT_LEAST_ONCE]]]
13:01:55.325 [pulsar-io-29-1] ERROR io.streamnative.pulsar.handlers.mqtt.support.ProtocolMethodProcessorImpl - [persistent://public/default/my-topic] [7f000001e3e460bf5c32] Failed to create subscription on Pulsar topic.
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/apache/pulsar/common/api/proto/PulsarApi$CommandSubscribe$InitialPosition
               at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
               at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) [?:?]
               at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) [?:?]
               at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) [?:?]
               at io.streamnative.pulsar.handlers.mqtt.utils.PulsarTopicUtils.getOrCreateSubscription(PulsarTopicUtils.java:44) ~[pulsar-protocol-handler-mqtt-2.8.0-SNAPSHOT.nar-unpacked/:?]
               at io.streamnative.pulsar.handlers.mqtt.support.ProtocolMethodProcessorImpl.processSubscribe(ProtocolMethodProcessorImpl.java:268) [pulsar-protocol-handler-mqtt-2.8.0-SNAPSHOT.nar-unpacked/:?]
               at io.streamnative.pulsar.handlers.mqtt.MQTTInboundHandler.channelRead(MQTTInboundHandler.java:60) [pulsar-protocol-handler-mqtt-2.8.0-SNAPSHOT.nar-unpacked/:?]
               at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.63.Final.jar:4.1.63.Final]

**Comment by andrekramer1** [comment]
This is happening for me on latest Pulsar snapshot on github. I was able to get a 2.7.0 of Pulsar standalone to work. So is it just a matter of dependency version?

**Comment by andrekramer1** [comment]
Seems https://github.com/apache/pulsar/blob/branch-2.7/pulsar-common/src/main/java/org/apache/pulsar/common/api/proto/PulsarApi.java was removed in 2.8.0. It was generated code that seems to now generated without the "PulsarApi" container (for nested classes) class.

**Comment by codelipenghui** [comment]
@andrekramer1 https://github.com/streamnative/mop/pull/65 this PR fixed the issue. so close for now.
