### ISSUE TITLE
Proxy write to broker failed.

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/mop#626]
```java
2022-05-09T07:11:57,489+0000 [mqtt-proxy-adapter-65-1] ERROR io.streamnative.pulsar.handlers.mqtt.adapter.AdapterChannel - [AdapterChannel] Proxy write to broker /127.0.0.1:1883 message MqttAdapterMessage(version=0, clientId=ip-10-0-0-119_bench_pub_42031_602499507, mqttMessage=MqttPublishMessage[fixedHeader=MqttFixedHeader[messageType=PUBLISH, isDup=false, qosLevel=AT_MOST_ONCE, isRetain=false, remainingLength=270], variableHeader=MqttPublishVariableHeader[topicName=bench/42031, packetId=-1], payload=PooledSlicedByteBuf(ridx: 0, widx: 256, cap: 256/256, unwrapped: PooledUnsafeDirectByteBuf(ridx: 273, widx: 273, cap: 416))], encodeType=ADAPTER_MESSAGE) failed.
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at io.streamnative.pulsar.handlers.mqtt.utils.FutureUtils.lambda$completableFuture$0(FutureUtils.java:32) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:723) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:308) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:660) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:735) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.handleWriteError(AbstractChannel.java:950) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:933) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:570) [io.netty-netty-transport-classes-epoll-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) [io.netty-netty-transport-classes-epoll-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-classes-epoll-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
2022-05-09T07:11:57,489+0000 [mqtt-proxy-adapter-65-1] ERROR io.streamnative.pulsar.handlers.mqtt.proxy.MQTTProxyProtocolMethodProcessor - [Proxy Publish] Failed to publish for topic : bench/42031, CId : ip-10-0-0-119_bench_pub_42031_602499507
io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
```

**Comment by goncalocribeiro** [comment]
Hi @mattisonchao.
What was the fix to this issue? I'm having the exact same problem with version 2.11.0.5.

Everything is just working fine and after some time (random) this error just occurrs.
Then I have to restart the broker to bypass the problem

**Comment by mattisonchao** [comment]
HI, @goncalocribeiro 
Could you try 3.0.x?

**Comment by goncalocribeiro** [comment]
> HI, @goncalocribeiro 
> 
> Could you try 3.0.x? 

Is it compatible with Pulsar 2.11.x ?
