### ISSUE TITLE
mac os uses mqtt to report an error: Lorg/apache/pulsar/broker/ServiceConfiguration;)Ljava/lang/String;

### ISSUE THREAD

**Issue by beyondyinjl2** [streamnative/mop#86]
macos big sur11.4
apache-pulsar-2.8.0/protocols/
2 versions
pulsar-protocol-handler-mqtt-2.9.0-SNAPSHOT.nar 
pulsar-protocol-handler-mqtt-2.8.0.8.nar 

vim conf/standalone.conf 
messagingProtocols=mqtt
 protocolHandlerDirectory=./protocols
brokerServicePort=6651
mqttListeners=mqtt://127.0.0.1:1883
 advertisedAddress=127.0.0.1

 mqttProxyEnable=true
 mqttProxyPort=5682

start pulsar
bin/pulsar standalone  

error:
ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
java.lang.NoSuchMethodError: org.apache.pulsar.broker.PulsarService.advertisedAddress(Lorg/apache/pulsar/broker/ServiceConfiguration;)Ljava/lang/String;
	at io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler.start(MQTTProtocolHandler.java:95) ~[?:?]
	at org.apache.pulsar.broker.protocol.ProtocolHandlerWithClassLoader.start(ProtocolHandlerWithClassLoader.java:66) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
	at org.apache.pulsar.broker.protocol.ProtocolHandlers.lambda$start$4(ProtocolHandlers.java:142) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_171]
	at org.apache.pulsar.broker.protocol.ProtocolHandlers.start(ProtocolHandlers.java:142) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:785) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:296) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:121) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
16:12:37.229 [Thread-1] INFO  org.apache.pulsar.broker.service.GracefulExecutorServicesTerminationHandler - Starting termination handler for 4 executors.
16:12:37.229 [globalEventExecutor-2-2] INFO  org.apache.pulsar.broker.service.GracefulExecutorServicesTerminationHandler - Starting termination handler for 7 executors.
16:12:37.230 [Thread-1] INFO  org.apache.pulsar.broker.service.GracefulExecutorServicesTerminationHandler - Shutdown completed.
16:12:37.230 [globalEventExecutor-2-2] INFO  org.apache.pulsar.broker.service.GracefulExecutorServicesTerminationHandler - Shutdown completed.
16:12:37.386 [Thread-1] ERROR org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=855,loopId=41e400ad) Error writing metadata to store
org.apache.bookkeeper.client.BKException$BKClientClosedException: BookKeeper client is closed
	at org.apache.bookkeeper.meta.CleanupLedgerManager.close(CleanupLedgerManager.java:245) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
	at org.apache.bookkeeper.client.BookKeeper.close(BookKeeper.java:1439) ~[org.apache.bookkeeper-bookkeeper-server-4.14.1.jar:4.14.1]
	at org.apache.distributedlog.BookKeeperClient.close(BookKeeperClient.java:273) ~[org.apache.distributedlog-distributedlog-core-4.14.1.jar:4.14.1]
	at org.apache.distributedlog.impl.BKNamespaceDriver.doClose(BKNamespaceDriver.java:404) ~[org.apache.distributedlog-distributedlog-core-4.14.1.jar:4.14.1]
	at org.apache.distributedlog.impl.BKNamespaceDriver.close(BKNamespaceDriver.java:385) ~[org.apache.distributedlog-distributedlog-core-4.14.1.jar:4.14.1]
	at com.google.common.io.Closeables.close(Closeables.java:78) ~[com.google.guava-guava-30.1-jre.jar:?]
	at org.apache.distributedlog.util.Utils.close(Utils.java:544) ~[org.apache.distributedlog-distributedlog-core-4.14.1.jar:4.14.1]
	at org.apache.distributedlog.BKDistributedLogNamespace.close(BKDistributedLogNamespace.java:340) ~[org.apache.distributedlog-distributedlog-core-4.14.1.jar:4.14.1]
	at org.apache.bookkeeper.stream.server.service.DLNamespaceProviderService.doClose(DLNamespaceProviderService.java:135) ~[org.apache.bookkeeper-stream-storage-server-4.14.1.jar:4.14.1]
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:123) ~[org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$close$6(LifecycleComponentStack.java:154) ~[org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406) [com.google.guava-guava-30.1-jre.jar:?]
	at org.apache.bookkeeper.common.component.LifecycleComponentStack.close(LifecycleComponentStack.java:154) [org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
	at org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent.doClose(StreamStorageLifecycleComponent.java:60) [org.apache.bookkeeper-stream-storage-server-4.14.1.jar:4.14.1]
	at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:123) [org.apache.bookkeeper-bookkeeper-common-4.14.1.jar:4.14.1]
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.stop(LocalBookkeeperEnsemble.java:492) [org.apache.pulsar-pulsar-zookeeper-utils-2.8.0.jar:2.8.0]
	at org.apache.pulsar.PulsarStandaloneStarter$1.run(PulsarStandaloneStarter.java:102) [org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]

**Comment by liangyuanpeng** [comment]
Same problem. 

OS:Centos7. 
Pulsar: 2.8.0
mop: master

**Comment by liangyuanpeng** [comment]
Finally i use released nar file `pulsar-protocol-handler-mqtt-2.7.1.4.nar` started, finally..

**Comment by liangyuanpeng** [comment]
This error of reason is pulsar master change the method `advertisedAddress` and i think pulsar 2.8.1 is ok.

**Comment by beyondyinjl2** [comment]
> Finally i use released nar file `pulsar-protocol-handler-mqtt-2.7.1.4.nar` and `pulsar 2.7.2` started, finally..

I also tried it. This version is ok, but there is no authentication function. I need the authentication function of mqtt. Could you please tell me where to modify it, it can be used quickly, instead of waiting for 2.8.1 to come out

**Comment by Technoboy-** [comment]
You should keep the pulsar version the same as mop version.
